/**
 * B-01: Preview Brief Data Contract — Source of Truth
 *
 * Formalizuje datový kontrakt mezi Apps Script (CRM backend) a preview
 * renderer. Definuje:
 * - CRM-side brief shape (as-is z buildPreviewBrief_ v PreviewPipeline.gs)
 * - Minimal compatible render request/response (zpětně kompatibilní s GAS)
 * - Recommended target render request/response (budoucí iterace)
 * - Validation tiers pro renderer
 *
 * Klasifikace tvrzení:
 * - VERIFIED IN REPO = ověřeno v apps-script/*.gs kódu
 * - PROPOSED CONTRACT = nově definováno touto specifikací
 * - PROPOSED RENDER RULE = pravidlo pro renderer, neexistuje v GAS
 *
 * @see apps-script/PreviewPipeline.gs — buildPreviewBrief_()
 * @see apps-script/Config.gs — EXTENSION_COLUMNS, PREVIEW_STAGES
 * @see apps-script/Helpers.gs — resolveWebsiteState_()
 */

// ============================================================================
// Section IDs — VERIFIED IN REPO
// buildPreviewBrief_() always starts with ['hero','services','contact'],
// conditionally adds 'location' (city||area), 'reviews' (rating>=3.5),
// 'faq' (painPoint non-empty).
// ============================================================================

export type SectionId = 'hero' | 'services' | 'contact' | 'reviews' | 'location' | 'faq';

// ============================================================================
// Website Status — VERIFIED IN REPO
// resolveWebsiteState_() in Helpers.gs returns UPPERCASE values.
// buildPreviewBrief_() stores .toLowerCase() in brief.
// ============================================================================

export type WebsiteStatusValue =
  | 'no_website'
  | 'weak_website'
  | 'has_website'
  | 'conflict'
  | 'unknown';

// ============================================================================
// Confidence Level — VERIFIED IN REPO
// Computed in buildPreviewBrief_(): score 0-6 →
//   >=5: 'high', >=3: 'medium', <3: 'low'
// ============================================================================

export type ConfidenceLevelValue = 'high' | 'medium' | 'low';

// ============================================================================
// Template Types — VERIFIED IN REPO
// chooseTemplateType_() in PreviewPipeline.gs generates base+suffix combos.
// ============================================================================

export type TemplateBase =
  | 'instalater'
  | 'electrician'
  | 'locksmith'
  | 'painter'
  | 'mason'
  | 'cleaning'
  | 'gardener'
  | 'auto-service'
  | 'beauty'
  | 'restaurant'
  | 'local-service'
  | 'emergency-service';

export type TemplateSuffix =
  | ''
  | '-no-website'
  | '-weak-website'
  | '-data-conflict'
  | '-basic';

export type TemplateType = `${TemplateBase}${TemplateSuffix}`;

// ============================================================================
// Preview Brief — VERIFIED IN REPO
// Exact 18-field shape returned by buildPreviewBrief_() in PreviewPipeline.gs.
// All fields ALWAYS present (never undefined/null). Missing data → "" or [].
// ============================================================================

/**
 * CRM-side preview brief as generated by Apps Script.
 *
 * All fields are always present (never undefined/null). Empty data → "" or [].
 * This is the as-is shape stored in the `preview_brief_json` LEADS column.
 *
 * Validation tiers (PROPOSED RENDER RULES):
 *
 * HARD FAIL (renderer must reject if empty):
 *   business_name, city, headline, suggested_sections (min 3)
 *
 * DEGRADED RENDER (renderer continues with simplified output):
 *   subheadline → hero shows only H1
 *   key_benefits → services section without benefit cards
 *   cta → fallback text "Kontaktujte nás"
 *
 * ENRICHMENT (improves quality, not required):
 *   website_status, confidence_level, contact_phone, contact_email,
 *   contact_name, area, service_type, segment, pain_point, rating,
 *   reviews_count
 *
 * GAS generation guarantees (VERIFIED IN REPO):
 *   headline — always non-empty (buildNaturalHeadline_ fallback chain)
 *   subheadline — always non-empty (buildNaturalSubheadline_ fallback)
 *   cta — always non-empty (fallback: "Kontaktujte nás")
 *   suggested_sections — always min 3 (hero, services, contact)
 *   website_status — always non-empty (resolveWebsiteState_ always returns)
 *   confidence_level — always non-empty (computed score)
 *
 * suggested_sections renderer requirement: min 3 items.
 * GAS always generates min 3. Renderer matches this guarantee.
 */
export interface PreviewBrief {
  /** HARD FAIL if empty. GAS: may be "". */
  business_name: string;
  /** ENRICHMENT. GAS: may be "". */
  contact_name: string;
  /** HARD FAIL if empty. GAS: may be "". */
  city: string;
  /** ENRICHMENT. GAS: may be "". */
  area: string;
  /** ENRICHMENT. GAS: may be "". */
  service_type: string;
  /** ENRICHMENT. GAS: may be "". */
  segment: string;
  /** ENRICHMENT. GAS: may be "". */
  pain_point: string;
  /** HARD FAIL if empty. GAS: always non-empty (fallback chain). */
  headline: string;
  /** DEGRADED RENDER if empty — hero shows only H1. GAS: always non-empty. */
  subheadline: string;
  /** DEGRADED RENDER if empty — services section without cards. GAS: may be []. */
  key_benefits: string[];
  /** HARD FAIL if empty. GAS: always min 3. Renderer requires min 3. */
  suggested_sections: SectionId[];
  /** DEGRADED RENDER if empty — fallback: "Kontaktujte nás". GAS: always non-empty. */
  cta: string;
  /** ENRICHMENT. GAS: may be "". */
  contact_phone: string;
  /** ENRICHMENT. GAS: may be "". */
  contact_email: string;
  /** ENRICHMENT. GAS: always non-empty (lowercase from resolveWebsiteState_). */
  website_status: WebsiteStatusValue;
  /** ENRICHMENT. GAS: may be "". String type, numeric when present. */
  rating: string;
  /** ENRICHMENT. GAS: may be "". String type. */
  reviews_count: string;
  /** ENRICHMENT. GAS: always non-empty (computed). */
  confidence_level: ConfidenceLevelValue;
}

// ============================================================================
// Minimal Compatible Contract — PROPOSED CONTRACT
// Backward-compatible with existing GAS processPreviewQueue() code.
// Only change needed in GAS: add preview_slug to webhook payload (1 line).
// ============================================================================

/**
 * Minimal compatible render request.
 * Based on existing webhook payload in processPreviewQueue().
 * preview_slug is the only addition (VERIFIED: missing from current payload).
 */
export interface MinimalRenderRequest {
  /** VERIFIED IN REPO */
  spreadsheet_id: string;
  /** VERIFIED IN REPO */
  sheet_name: string;
  /** VERIFIED IN REPO */
  row_number: number;
  /** VERIFIED IN REPO */
  company_key: string;
  /** VERIFIED IN REPO */
  branch_key: string;
  /** VERIFIED IN REPO */
  template_type: TemplateType;
  /** VERIFIED IN REPO — the 18-field brief object */
  preview_brief: PreviewBrief;
  /** VERIFIED IN REPO — redundant with brief contact fields */
  contact: {
    name: string;
    phone: string;
    email: string;
  };
  /** VERIFIED IN REPO */
  source: {
    lead_id: string;
    source: string;
    created_at: string;
    segment: string;
    city: string;
  };
  /** VERIFIED IN REPO — ISO 8601 */
  timestamp: string;
  /** PROPOSED CONTRACT — gap fix: exists in LEADS but missing from payload */
  preview_slug: string;
}

/**
 * Minimal compatible render response — success.
 * Matches exactly what GAS processPreviewQueue() currently parses.
 *
 * preview_quality_score: CONTRACT CONCLUSION — number, scale 0.0–1.0.
 * GAS compares < 0.7 to determine needs_review.
 */
export interface MinimalRenderResponseOk {
  /** VERIFIED IN REPO — GAS checks respObj.ok */
  ok: true;
  /** VERIFIED IN REPO — written to LEADS preview_url */
  preview_url: string;
  /** VERIFIED IN REPO — written to LEADS preview_screenshot_url */
  preview_screenshot_url?: string;
  /** VERIFIED IN REPO — written to LEADS preview_version */
  preview_version?: string;
  /** VERIFIED IN REPO — scale 0.0–1.0 (CONTRACT CONCLUSION). GAS: < 0.7 = needs review. */
  preview_quality_score?: number;
  /** VERIFIED IN REPO — GAS: true OR quality_score < 0.7 = needs review */
  preview_needs_review?: boolean;
}

/** Minimal compatible render response — error. GAS reads respBody.substring(0,300). */
export interface MinimalRenderResponseError {
  /** VERIFIED IN REPO */
  ok: false;
}

export type MinimalRenderResponse = MinimalRenderResponseOk | MinimalRenderResponseError;

// ============================================================================
// Recommended Target Contract — PROPOSED CONTRACT
// Cleaner version for future iteration. Requires GAS payload restructuring.
// ============================================================================

/**
 * Target render request — simplified.
 * Removes internal GAS metadata, adds contract_version.
 */
export interface TargetRenderRequest {
  /** PROPOSED CONTRACT — semver, initial "1.0" */
  contract_version: string;
  /** VERIFIED IN REPO (existing in payload) */
  template_type: TemplateType;
  /** PROPOSED CONTRACT — gap fix */
  preview_slug: string;
  /** VERIFIED IN REPO (from payload.source.lead_id) — promoted */
  lead_id: string;
  /** VERIFIED IN REPO (existing in payload) */
  preview_brief: PreviewBrief;
  /** VERIFIED IN REPO (as timestamp) — renamed */
  requested_at: string;
}

/** PROPOSED CONTRACT — structured error codes */
export type PreviewErrorCode =
  | 'INVALID_BRIEF'
  | 'UNKNOWN_TEMPLATE'
  | 'SLUG_CONFLICT'
  | 'RENDER_FAILED'
  | 'TIMEOUT';

/** Target render response — success. Same fields as minimal. */
export interface TargetRenderResponseOk {
  ok: true;
  preview_url: string;
  preview_screenshot_url?: string;
  preview_version?: string;
  /** Scale 0.0–1.0 (CONTRACT CONCLUSION) */
  preview_quality_score?: number;
  preview_needs_review?: boolean;
}

/** Target render response — error. Adds structured error fields. */
export interface TargetRenderResponseError {
  ok: false;
  /** PROPOSED CONTRACT */
  error_code?: PreviewErrorCode;
  /** PROPOSED CONTRACT */
  error_message?: string;
}

export type TargetRenderResponse = TargetRenderResponseOk | TargetRenderResponseError;

export type PreviewRenderResponse = TargetRenderResponse;
